<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Authors>attick, Zeffuro</Authors>
    <Company></Company>
    <Version>1.0.2.6</Version>
    <Description>Ants in your /pants!</Description>
    <Copyright></Copyright>
    <PackageProjectUrl>https://github.com/Zeffuro/AbilityAntsPlugin</PackageProjectUrl>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Platforms>x64</Platforms>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);CA1416</NoWarn>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>
</Project>
